// ── Firebase Configuration ─────────────────────────────────
// Replace these placeholder values with your Firebase project credentials
// to enable Cloud Mode (auth + Firestore). Leave as-is for Local Mode (LocalStorage).
const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
  measurementId: "",
};

const collections = [
  {
    id: "monster",
    title: "Monster Energy",
    description: "Flavor variants, tabs, ratings, and gas-station memories.",
    count: 5,
    visibility: "Private",
    tags: ["energy", "cans", "flavors"],
    accent: "radial-gradient(circle at 50% 55%, #fcfb09 0%, rgba(252, 251, 9, 0.5) 25%, rgba(252, 251, 9, 0.15) 60%, rgba(252, 251, 9, 0) 90%), #fcfedf",
  },
  {
    id: "perfume",
    title: "Perfumes",
    description: "Scent notes, season, bottle photos, and personal moods.",
    count: 2,
    visibility: "Public",
    tags: ["scent", "seasonal", "notes"],
    accent: "radial-gradient(circle at 50% 55%, #ff5eb8 0%, rgba(255, 94, 184, 0.5) 25%, rgba(255, 94, 184, 0.15) 60%, rgba(255, 94, 184, 0) 90%), #fff1f8",
  },
  {
    id: "vinyl",
    title: "Vinyl",
    description: "Pressings, sleeve condition, shops, and listening notes.",
    count: 2,
    visibility: "Private",
    tags: ["pressing", "sleeve", "listening"],
    accent: "radial-gradient(circle at 50% 55%, #9d65ff 0%, rgba(157, 101, 255, 0.5) 25%, rgba(157, 101, 255, 0.15) 60%, rgba(157, 101, 255, 0) 90%), #f6f3ff",
  },
  {
    id: "plants",
    title: "Plants",
    description: "Growth logs, watering rhythm, propagation, and shelf spots.",
    count: 2,
    visibility: "Friends",
    tags: ["growth", "watering", "shelf"],
    accent: "radial-gradient(circle at 50% 55%, #00cbb6 0%, rgba(0, 203, 182, 0.5) 25%, rgba(0, 203, 182, 0.15) 60%, rgba(0, 203, 182, 0) 90%), #e5fbf9",
  },
];

const items = [
  {
    id: "item-1",
    collectionId: "monster",
    title: "",
    note: "",
    rating: 9.6,
    tags: [],
    added: "May 2026",
    status: "Owned",
    meta: {},
    art: "linear-gradient(135deg, #caff6a, #26d482 52%, #111318)",
  },
  {
    id: "item-2",
    collectionId: "monster",
    title: "",
    note: "",
    rating: 8.8,
    tags: [],
    added: "Apr 2026",
    status: "Owned",
    meta: {},
    art: "linear-gradient(135deg, #ffca3a, #ff7a3d 48%, #1a8cff)",
  },
  {
    id: "item-3",
    collectionId: "monster",
    title: "",
    note: "",
    rating: 9.1,
    tags: [],
    added: "May 2026",
    status: "Owned",
    meta: {},
    art: "linear-gradient(135deg, #ffb199, #ff5e8a 46%, #8fd3ff)",
  },
  {
    id: "item-4",
    collectionId: "monster",
    title: "",
    note: "",
    rating: 8.4,
    tags: [],
    added: "Mar 2026",
    status: "Owned",
    meta: {},
    art: "linear-gradient(135deg, #e21b3c, #ff8f3d 50%, #ffe46a)",
  },
  {
    id: "item-5",
    collectionId: "monster",
    title: "",
    note: "",
    rating: null,
    tags: [],
    added: "Feb 2026",
    status: "Wishlist",
    meta: {},
    art: "linear-gradient(135deg, #111318, #ff7a3d 42%, #14d0ff)",
  },
  {
    id: "item-6",
    collectionId: "monster",
    title: "",
    note: "",
    rating: 8.2,
    tags: [],
    added: "Jan 2026",
    status: "Owned",
    meta: {},
    art: "linear-gradient(135deg, #fff17a, #47d2ff 46%, #1f55ff)",
  },
  {
    id: "item-7",
    collectionId: "perfume",
    title: "",
    note: "",
    rating: 9.3,
    tags: [],
    added: "May 2026",
    status: "Owned",
    meta: {},
    art: "linear-gradient(135deg, #ff9eba, #ff5eb8 50%, #7a0046)",
  },
  {
    id: "item-8",
    collectionId: "perfume",
    title: "",
    note: "",
    rating: 8.0,
    tags: [],
    added: "Apr 2026",
    status: "Wishlist",
    meta: {},
    art: "linear-gradient(135deg, #e0f7fa, #80deea 48%, #00acc1)",
  },
  {
    id: "item-9",
    collectionId: "vinyl",
    title: "",
    note: "",
    rating: 9.8,
    tags: [],
    added: "Apr 2026",
    status: "Owned",
    meta: {},
    art: "linear-gradient(135deg, #8a73ff, #473bff 52%, #111)",
  },
  {
    id: "item-10",
    collectionId: "vinyl",
    title: "",
    note: "",
    rating: 9.5,
    tags: [],
    added: "Mar 2026",
    status: "Wishlist",
    meta: {},
    art: "linear-gradient(135deg, #ff7a3d, #ff5e8a 48%, #0a58ff)",
  },
  {
    id: "item-11",
    collectionId: "plants",
    title: "",
    note: "",
    rating: 9.4,
    tags: [],
    added: "May 2026",
    status: "Owned",
    meta: {},
    art: "linear-gradient(135deg, #a8ff78, #78ffd6 50%, #00a896)",
  },
  {
    id: "item-12",
    collectionId: "plants",
    title: "",
    note: "",
    rating: 8.1,
    tags: [],
    added: "Jan 2026",
    status: "Wishlist",
    meta: {},
    art: "linear-gradient(135deg, #fff27a, #a8ff78 48%, #1f5f2f)",
  },
];

const state = {
  screen: "collections",
  previousScreen: "collections",
  collectionId: "monster",
  selectedItemId: "item-3",
  view: "grid",
  status: "all",
  sort: "custom",
  activeTag: null,
  search: "",
  draftTags: [],
  photoSource: "album",
  extractedImage: "",
  batchMode: false,
  selectedItems: new Set(),
  editDraftTags: [],
  editExtractedImage: "",
  deckIndex: 0,
  holisticView: false,
  lang: "en",
};

const i18n = {
  en: {
    screenCollectionsKicker: "Collections",
    screenCollectionsTitle: "Collections",
    screenSettingsKicker: "Settings",
    screenSettingsTitle: "Preferences",
    itemsCount: "items",
    itemsCountSingle: "item",
    visibilityPrivate: "Private",
    visibilityPublic: "Public",
    visibilityFriends: "Friends",
    logoutToast: "Logged out successfully",
    toastExport: "Collection data exported!",
    toastExportFail: "Failed to export data",
    toastCache: "Image cache cleared! Freed 14.2 MB",
    toastLangChanged: "Language switched to English",
    noMatches: "No matches",
    noMatchesSub: "Try another rating, added time, or tag filter.",
    noTags: "No tags added yet",
    batchSelected: "selected",
    batchDeletePrompt: "Batch Select & Delete",
    manageSpace: "Manage Space",
    editCollection: "Edit Collection",
    renameCollection: "Rename Collection",
    renameBtn: "Rename",
    editCollectionColorLabel: "Card Color",
    batchActions: "Batch Actions",
    manualReordering: "Manual Reordering",
    manualReorderingSub: "Move items up or down to set a custom ordering.",
    owned: "Owned",
    wishlist: "Wishlist",
    archived: "Archived",
    dangerZone: "Danger Zone",
    deleteCollectionBtn: "Delete Collection",
    summaryCollections: "Collections",
    summaryTotalItems: "Total items",
    summaryOwned: "Owned",
    summaryLastCollected: "Last collected",
    seeAll: "See All",
    swipeToBrowse: "Swipe to browse",
    backToDeck: "Back to deck",
    newCollection: "New Collection",
    addCollectionSpaceLabel: "New Space",
    addCollectionHeading: "New Collection",
    addCollectionTitleLabel: "Title",
    addCollectionTitlePlaceholder: "Collection name",
    addCollectionDescLabel: "Description",
    addCollectionDescPlaceholder: "Describe your collection...",
    addCollectionColorLabel: "Background Accent Color",
    addCollectionVisibilityLabel: "Sharing & Visibility",
    addCollectionSubmitBtn: "Create collection",
    selectCollectionPlaceholder: "Select a collection",
    toastCollectionCreated: '"{name}" created',
    addCollectionSelectLabel: "Collection",
    addChoiceSpaceLabel: "Add New",
    addChoiceHeading: "Select Option",
    choiceAddCollectionTitle: "Create Collection",
    choiceAddCollectionDesc: "Create a new space to organize items",
    choiceAddItemTitle: "Add Item",
    choiceAddItemDesc: "Add an item to the collection: {name}",
    settingsPreferences: "Preferences",
    settingsLanguageLabel: "Language",
    settingsLanguageDesc: "Select your preferred interface language",
    settingsAccount: "Account",
    settingsLogoutLabel: "Log Out",
    settingsLogoutDesc: "Sign out of this device safely",
    settingsProfileSub: "Curator since 2024 • Pro Member",
    shareCollectionLabel: "Share Collection",
    shareCollectionBtn: "📤 Share Collection List",
    toastShareSuccess: "Collection list copied to clipboard!",
    toastShareFail: "Failed to share or copy collection list",
    authWelcomeTitle: "Welcome to Archive",
    authWelcomeSub: "Your personal collection tracker",
    authEmailLabel: "Email",
    authEmailPlaceholder: "your@email.com",
    authPasswordLabel: "Password",
    authPasswordPlaceholder: "••••••••",
    authSignIn: "Sign In",
    authSignUp: "Create Account",
    authSwitchToSignUp: "Don't have an account?",
    authSwitchToSignIn: "Already have an account?",
    authSwitchSignUpBtn: "Sign Up",
    authSwitchSignInBtn: "Sign In",
    authError: "Authentication failed. Please try again.",
    authErrorInvalidEmail: "Please enter a valid email address.",
    authErrorWrongPassword: "Incorrect password. Please try again.",
    authErrorUserNotFound: "No account found with this email.",
    authErrorEmailInUse: "This email is already registered.",
    authErrorWeakPassword: "Password must be at least 6 characters.",
    authToastSignedIn: "Signed in successfully!",
    authToastSignedUp: "Account created successfully!",
    authToastSignedOut: "Signed out successfully",
    settingsProfileCloud: "Cloud Mode • Synced",
    settingsProfileLocal: "Local Mode • Browser Only",
    settingsData: "Data",
    settingsExportLabel: "Export Data",
    settingsExportDesc: "Download all collections & items as a spreadsheet",
    settingsClearLabel: "Clear Data",
    settingsClearDesc: "Erase all collections & items from this browser",
    profileEditKicker: "Profile",
    profileEditHeading: "Edit Profile",
    profileNameLabel: "Name",
    profileBioLabel: "Bio",
    profileNamePlaceholder: "Your name",
    profileBioPlaceholder: "A short bio",
    profileSaveBtn: "Save Changes",
    profileChangePhoto: "Change Photo",
    profileRemovePhoto: "Remove",
    profileSavedToast: "Profile updated",
    profileDefaultName: "Local User",
    profileDefaultBio: "Local Mode • Browser Only",
    confirmClearTitle: "Clear all data?",
    confirmClearMessage: "This permanently deletes all your collections and items stored in this browser. This can't be undone.",
    confirmCancel: "Cancel",
    confirmClearBtn: "Clear Data",
    clearedToast: "All data cleared",
    exportEmptyToast: "Nothing to export yet",
    exportDoneToast: "Exported {n} item(s) to a spreadsheet",
  },
  zh: {
    screenCollectionsKicker: "我的收藏",
    screenCollectionsTitle: "收藏",
    screenSettingsKicker: "设置",
    screenSettingsTitle: "偏好设置",
    itemsCount: "件单品",
    itemsCountSingle: "件单品",
    visibilityPrivate: "私有",
    visibilityPublic: "公开",
    visibilityFriends: "仅限好友",
    logoutToast: "已成功退出登录",
    toastExport: "收藏数据已导出！",
    toastExportFail: "导出数据失败",
    toastCache: "图片缓存已清理！释放了 14.2 MB",
    toastLangChanged: "语言已切换为中文",
    noMatches: "无匹配项",
    noMatchesSub: "请尝试使用其他评分、添加时间或标签过滤条件。",
    noTags: "暂无标签",
    batchSelected: "已选择",
    batchDeletePrompt: "批量选择与删除",
    manageSpace: "管理空间",
    editCollection: "编辑收藏夹",
    renameCollection: "重命名收藏夹",
    renameBtn: "重命名",
    editCollectionColorLabel: "卡片颜色",
    batchActions: "批量操作",
    manualReordering: "手动排序",
    manualReorderingSub: "拖动或使用按钮上下移动项目以自定义排序方式。",
    owned: "已拥有",
    wishlist: "心愿单",
    archived: "已归档",
    dangerZone: "危险区域",
    deleteCollectionBtn: "删除收藏夹",
    summaryCollections: "收藏夹",
    summaryTotalItems: "单品总数",
    summaryOwned: "已拥有/心愿单",
    summaryLastCollected: "最近收集",
    seeAll: "查看全部",
    swipeToBrowse: "左右滑动浏览",
    backToDeck: "返回卡片流",
    newCollection: "新建收藏",
    addCollectionSpaceLabel: "新空间",
    addCollectionHeading: "创建收藏夹",
    addCollectionTitleLabel: "标题",
    addCollectionTitlePlaceholder: "收藏夹名称",
    addCollectionDescLabel: "描述",
    addCollectionDescPlaceholder: "描述您的收藏夹...",
    addCollectionColorLabel: "卡片背景主题色",
    addCollectionVisibilityLabel: "分享与可见性",
    addCollectionSubmitBtn: "创建收藏夹",
    toastCollectionCreated: '已创建 "${name}"',
    selectCollectionPlaceholder: "选择收藏夹",
    addCollectionSelectLabel: "隶属收藏夹",
    addChoiceSpaceLabel: "添加新内容",
    addChoiceHeading: "选择选项",
    choiceAddCollectionTitle: "新建收藏夹",
    choiceAddCollectionDesc: "创建一个新的空间来整理单品",
    choiceAddItemTitle: "添加单品",
    choiceAddItemDesc: "向收藏夹「{name}」添加单品",
    settingsPreferences: "偏好设置",
    settingsLanguageLabel: "语言",
    settingsLanguageDesc: "选择您的界面语言",
    settingsAccount: "账户",
    settingsLogoutLabel: "退出登录",
    settingsLogoutDesc: "安全退出当前设备",
    settingsProfileSub: "自 2024 年起担任策展人 • 专业会员",
    shareCollectionLabel: "分享收藏夹",
    shareCollectionBtn: "📤 分享收藏单品列表",
    toastShareSuccess: "已成功复制收藏单品列表到剪贴板！",
    toastShareFail: "分享或复制收藏夹失败，请重试",
    authWelcomeTitle: "欢迎使用 Archive",
    authWelcomeSub: "您的私人收藏追踪器",
    authEmailLabel: "邮箱",
    authEmailPlaceholder: "your@email.com",
    authPasswordLabel: "密码",
    authPasswordPlaceholder: "••••••••",
    authSignIn: "登录",
    authSignUp: "创建账户",
    authSwitchToSignUp: "还没有账户？",
    authSwitchToSignIn: "已有账户？",
    authSwitchSignUpBtn: "注册",
    authSwitchSignInBtn: "登录",
    authError: "认证失败，请重试。",
    authErrorInvalidEmail: "请输入有效的邮箱地址。",
    authErrorWrongPassword: "密码错误，请重试。",
    authErrorUserNotFound: "未找到该邮箱对应的账户。",
    authErrorEmailInUse: "该邮箱已被注册。",
    authErrorWeakPassword: "密码长度至少为6位。",
    authToastSignedIn: "登录成功！",
    authToastSignedUp: "账户创建成功！",
    authToastSignedOut: "已成功退出登录",
    settingsProfileCloud: "云端模式 • 已同步",
    settingsProfileLocal: "本地模式 • 仅限浏览器",
    settingsData: "数据",
    settingsExportLabel: "导出数据",
    settingsExportDesc: "将所有收藏和单品下载为表格",
    settingsClearLabel: "清除数据",
    settingsClearDesc: "清除此浏览器中的所有收藏和单品",
    profileEditKicker: "个人资料",
    profileEditHeading: "编辑资料",
    profileNameLabel: "名称",
    profileBioLabel: "简介",
    profileNamePlaceholder: "你的名字",
    profileBioPlaceholder: "一句简介",
    profileSaveBtn: "保存更改",
    profileChangePhoto: "更换头像",
    profileRemovePhoto: "移除",
    profileSavedToast: "资料已更新",
    profileDefaultName: "本地用户",
    profileDefaultBio: "本地模式 • 仅限浏览器",
    confirmClearTitle: "清除所有数据？",
    confirmClearMessage: "此操作将永久删除此浏览器中存储的所有收藏和单品，且无法撤销。",
    confirmCancel: "取消",
    confirmClearBtn: "清除数据",
    clearedToast: "所有数据已清除",
    exportEmptyToast: "暂无可导出的数据",
    exportDoneToast: "已导出 {n} 件单品到表格",
  },
};
